config/routes.rb
Rails3RecipeBook::Application.routes.draw do
  get "welcome/index"

  resources :dlogs

  get "entry/index"

  get "entry/show"

  resources :blogs

  root :to => "welcome#index"

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/dlog.rb
class Dlog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.xml
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.xml
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.xml
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.xml
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to(@blog, :notice => 'Blog was successfully created.') }
        format.xml  { render :xml => @blog, :status => :created, :location => @blog }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.xml
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to(@blog, :notice => 'Blog was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.xml
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to(blogs_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/dlogs_controller.rb
class DlogsController < ApplicationController
  # GET /dlogs
  # GET /dlogs.xml
  def index
    @dlogs = Dlog.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dlogs }
      format.json { render :json => @dlogs }
    end
  end

  # GET /dlogs/1
  # GET /dlogs/1.xml
  def show
    @dlog = Dlog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dlog }
    end
  end

  # GET /dlogs/new
  # GET /dlogs/new.xml
  def new
    @dlog = Dlog.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dlog }
    end
  end

  # GET /dlogs/1/edit
  def edit
    @dlog = Dlog.find(params[:id])
  end

  # POST /dlogs
  # POST /dlogs.xml
  def create
    @dlog = Dlog.new(params[:dlog])

    respond_to do |format|
      if @dlog.save
        format.html { redirect_to(@dlog, :notice => 'Dlog was successfully created.') }
        format.xml  { render :xml => @dlog, :status => :created, :location => @dlog }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dlog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dlogs/1
  # PUT /dlogs/1.xml
  def update
    @dlog = Dlog.find(params[:id])

    respond_to do |format|
      if @dlog.update_attributes(params[:dlog])
        format.html { redirect_to(@dlog, :notice => 'Dlog was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dlog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dlogs/1
  # DELETE /dlogs/1.xml
  def destroy
    @dlog = Dlog.find(params[:id])
    @dlog.destroy

    respond_to do |format|
      format.html { redirect_to(dlogs_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/entry_controller.rb
class EntryController < ApplicationController
  def index
  end

  def show
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/dlogs_helper.rb
module DlogsHelper
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.name %></td>
    <td><%= blog.user_id %></td>
    <td><%= link_to 'Show', blog %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td><%= link_to 'Destroy', blog, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @blog.name %>
</p>

<p>
  <b>User:</b>
  <%= @blog.user_id %>
</p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/dlogs/_form.html.erb
<%= form_for(@dlog) do |f| %>
  <% if @dlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dlog.errors.count, "error") %> prohibited this dlog from being saved:</h2>

      <ul>
      <% @dlog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dlogs/edit.html.erb
<h1>Editing dlog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dlog %> |
<%= link_to 'Back', dlogs_path %>

app/views/dlogs/index.html.erb
<h1>Listing dlogs</h1>

<table>
  <tr>
    <th>User</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dlogs.each do |dlog| %>
  <tr>
    <td><%= dlog.user_id %></td>
    <td><%= dlog.title %></td>
    <td><%= link_to 'Show', dlog %></td>
    <td><%= link_to 'Edit', edit_dlog_path(dlog) %></td>
    <td><%= link_to 'Destroy', dlog, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dlog', new_dlog_path %>

app/views/dlogs/new.html.erb
<h1>New dlog</h1>

<%= render 'form' %>

<%= link_to 'Back', dlogs_path %>

app/views/dlogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @dlog.user_id %>
</p>

<p>
  <b>Title:</b>
  <%= @dlog.title %>
</p>


<%= link_to 'Edit', edit_dlog_path(@dlog) %> |
<%= link_to 'Back', dlogs_path %>

app/views/entry/index.html.erb
<h1>Entry#index</h1>
<p>Find me in app/views/entry/index.html.erb</p>

app/views/entry/show.html.erb
<h1>Entry#show</h1>
<p>Find me in app/views/entry/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3RecipeBook</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>